### ISSUE TITLE
Keeping major version

### ISSUE THREAD

**Issue by patwork** [se-panfilov/bower-check-updates#10]
Hi,

Is there a way to tell bower-check-updates to keep major version of particular packages? For example, I have:

```
"dependencies": {
"bootstrap": "3",
"jquery": "1",
"modernizr": "~2.8.3",
"countdown": "~2.1.0"
}
```

Output from bcu is like:

```
 jquery          1  →               2 
 modernizr  ~2.8.3  →  ~3.0.0-alpha.4 
 countdown  ~2.1.0  →          ~2.6.0 
```

I don't want to change jquery from 1.x.x to 2.x.x, but I still want to update to newest version from 1.x.x if available. I don't want alpha version of modernizr also (I didn't use --greatest option, so why it's showing me unstable version). In this case, I'm ok only with updating countdown, because I don't know if there is newer stable version of jquery 1.x.x or modernizr.

**Comment by PeterStAngelo** [comment]
I too am having problems with this...
    angular  1.4.5   > 1.5.0-beta.0 
I was expecting it to get 1.4.6

**Comment by ravishivt** [comment]
+1

**Comment by se-panfilov** [comment]
Library has depreciated, please use [npm-check-updates](https://github.com/tjunnone/npm-check-updates) instead :

```
//in bower mode
$ ncu -m bower
```
