### ISSUE TITLE
Change Update Text

### ISSUE THREAD

**Issue by floriandotorg** [se-panfilov/bower-check-updates#11]
Thanks for this wonderful tool.

You should change the update text, tough:
![bildschirmfoto 2015-08-24 um 16 25 04](https://cloud.githubusercontent.com/assets/6143734/9442536/b6233c82-4a7c-11e5-9f0b-9d3029911ada.png)

**Comment by ChrisPearce** [comment]
The following text could also benefit from being changed:
`The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your bower.json by using npm update.`

**Comment by ajaegle** [comment]
This is fixed with #14

**Comment by se-panfilov** [comment]
Merged, will be able in closest release
