### ISSUE TITLE
Updating to non-existent version

### ISSUE THREAD

**Issue by ravishivt** [se-panfilov/bower-check-updates#13]
My bower.json has `"angular-ui-select": "~0.12.1"`, which is the latest version of https://github.com/angular-ui/ui-select .  When running bower-check-updates, it wants to update the package to 0.12.10 which doesn't exist:

```
The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your bower.json by using npm update. If you want to update the dependency in your bower.json anyway, use bcu --upgradeAll.

 angular-ui-select  ~0.12.1  →  ~0.12.100
```

Is this a bug on bcu or on ui-select?

**Comment by se-panfilov** [comment]
Library has depreciated, please use [npm-check-updates](https://github.com/tjunnone/npm-check-updates) instead :

```
//in bower mode
$ ncu -m bower
```
