### ISSUE TITLE
Bower now officially supported in npm-check-updates

### ISSUE THREAD

**Issue by raineorshine** [se-panfilov/bower-check-updates#15]
Hi! Thanks for maintaining this repo while bower was unsupported in [npm-check-updates](https://github.com/tjunnone/npm-check-updates). It just landed in v2.3.0.

Not sure if you want to update the README and send people over there now. Let me know, I can submit a pull request for the README edit as well. Thanks!

**Comment by Toilal** [comment]
Thanks for the info !

**Comment by se-panfilov** [comment]
Done
