### ISSUE TITLE
Error running "bower-check-updates"

### ISSUE THREAD

**Issue by magnusosbeck** [se-panfilov/bower-check-updates#17]
Unhandled rejection TypeError: Cannot read property 'major' of undefined
    at /usr/local/lib/node_modules/bower-check-updates/lib/version-util.js:66:71
    at Array.filter (native)
    at Object.stringify (/usr/local/lib/node_modules/bower-check-updates/lib/version-util.js:65:10)
    at isUpgradeable (/usr/local/lib/node_modules/bower-check-updates/lib/versionmanager.js:162:31)
    at /usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:8201:21
    at /usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:4299:13
    at /usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:3073:15
    at baseForIn (/usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:2033:14)
    at pickByCallback (/usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:4298:7)
    at Function.<anonymous> (/usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:9893:11)
    at Function.pick (/usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:8152:31)
    at baseWrapperValue (/usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:2768:30)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/bower-check-updates/node_modules/lodash/index.js:6124:14)
    at Object.upgradeDependencies (/usr/local/lib/node_modules/bower-check-updates/lib/versionmanager.js:149:10)
    at /usr/local/lib/node_modules/bower-check-updates/lib/bower-check-updates.js:65:39
##     at tryCatcher (/usr/local/lib/node_modules/bower-check-updates/node_modules/bluebird/js/main/util.js:26:23)

{
  "name": "xxx",
  "description": "xxx",
  "version": "0.0.0",
  "homepage": "",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "~1.3.15",
    "angular-route": "~1.3.15",
    "angular-loader": "~1.3.15",
    "angular-mocks": "",
    "html5-boilerplate": "~4.3.0",
    "bootstrap": "~3.3.1",
    "jQuery": "~2.1.3",
    "Faker": "~2.1.2",
    "bootstrap-material-design": "~0.2.1",
    "angular-xeditable": "~0.1.8",
    "angular-animate": "1.3.15",
    "angular-sanitize": "1.3.15",
    "angular-redactor": "~1.1.0",
    "angular-growl": "~0.4.0",
    "angular-ui-router": "~0.2.13",
    "ng-file-upload": "~3.2.4",
    "ng-file-upload-shim": "~3.2.4",
    "videogular": "~1.1.1",
    "videogular-themes-default": "~1.1.1",
    "videogular-controls": "~1.1.1",
    "angular-modal-service": "~0.6.6",
    "angular-ui-select": "~0.11.2",
    "angular-websocket": "~1.0.9",
    "angular-loading-bar": "~0.7.1",
    "angular-bootstrap-datetimepicker": "~0.3.12",
    "angular-translate": "~2.6.1",
    "animate.css": "~3.2.6",
    "loaders.css": "~0.1.0",
    "ngInfiniteScroll": "~1.2.0",
    "angular-elastic": "~2.4.2",
    "angular-cache": "~4.6.0",
    "photoswipe": "~4.0.7",
    "angulartics": "~0.17.2",
    "ng-device-detector": "1.1.2"
  },
  "devDependencies": {
    "karma": "",
    "karma-jasmine": ""
  },
  "resolutions": {
    "angular": "~1.3.15"
  }
}

**Comment by raineorshine** [comment]
If this is an error in the original npm-check-updates code, I'm happy to take a look! You'll need to narrow down which package is causing the error first. I suggest removing half the dependencies at a time until the error goes away and you can identify which specific package causes the error. I have seen situations where packages are incorrectly published and the issues is with the package author.

**Comment by magnusosbeck** [comment]
npm-check-update works great, it’s the bower-check-update that fails. But i will try to find what package that is causing that fail.
I’ll get back to you.
Magnus Osbeck / Produkt- och konceptdesigner 
magnus.osbeck@lineducation.se mailto:magnus.osbeck@lineducation.se / 0702-626212

      http://www.lineducation.se/ 
Lin Education, #linedu 
Anders Carlssons gata 9  
417 55 Göteborg 
www.lineducation.se
 http://www.lineducation.se/ https://twitter.com/lineducation  https://www.facebook.com/LinEducation/  https://www.linkedin.com/company/lin-education  https://instagram.com/lineducation/
 http://www.lineducation.se/

**Comment by raineorshine** [comment]
Since this library is deprecated, you can always try running npm-check-updates in bower mode:

```
$ ncu -m bower
```

**Comment by magnusosbeck** [comment]
Hi, that worked great! Thanks.

Btw, i tried to remove all dependencies in both bower.json and package.json but i still got the error when running bower-check-updates.
But ncu -m bower worked great. Thanks
Magnus Osbeck / Produkt- och konceptdesigner 
magnus.osbeck@lineducation.se mailto:magnus.osbeck@lineducation.se / 0702-626212

      http://www.lineducation.se/ 
Lin Education, #linedu 
Anders Carlssons gata 9  
417 55 Göteborg 
www.lineducation.se
 http://www.lineducation.se/ https://twitter.com/lineducation  https://www.facebook.com/LinEducation/  https://www.linkedin.com/company/lin-education  https://instagram.com/lineducation/
 http://www.lineducation.se/

**Comment by raineorshine** [comment]
Good to hear! There was probably a patch to npm-check-updates that fixed
whatever it was, and bower-check-update is just not maintained any longer.
