### ISSUE TITLE
not working with node 7.10

### ISSUE THREAD

**Issue by patrikx3** [se-panfilov/bower-check-updates#18]
```(node:30637) DeprecationWarning: Calling an asynchronous function without callback is deprecated.```

**Comment by raineorshine** [comment]
Thanks for reporting! It looks like this is just a warning, so it at least is still functional. Is that true, or is it not working for you? We should get this cleared up in the next version either way.

**Comment by patrikx3** [comment]
ciao!!!
7.10 is broken, i like it since, i use ncu and bcu , even though ncu does it always, but i like it, keep it on you got some free time!!!

**Comment by patrikx3** [comment]
i guess it is deprecated, and use ncu for the future! thanks!

**Comment by se-panfilov** [comment]
@patrikx3 Yes, `bcu`  is absolutely deprecated for a long time, so there are no reasons to use it over `ncu`. Please switch to `ncu` and thanks for your time with `bcu` =)
