### ISSUE TITLE
Semver recognition issue

### ISSUE THREAD

**Issue by zenopopovici** [se-panfilov/bower-check-updates#9]
Hello,

Well it seems the recognition of new packages is somehow flawed:

```
 bcu
 modernizr  ~2.8.3  →  ~3.0.0-alpha.4 
 Run with -u to upgrade your bower.json
```

It should not prompt me to upgrade to pre-release, beta or alpha releases. modernizr uses correct semver versioning. Latest stable is: 2.8.3

What do you think?

**Comment by se-panfilov** [comment]
Yep, you right, but will be better to open an issue in [tjunnone/npm-check-updates](https://github.com/tjunnone/npm-check-updates), coz i'll loose patch anyway on the feature merges with tjunnone's repo.

**Comment by zenopopovici** [comment]
Seems he's working on integrating bower too. 
https://github.com/tjunnone/npm-check-updates/issues/43 

Maybe join the dark side together? :) J/K. Nice work tough!
